config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }
  
  scope '(:locale)', locale: /en|es/ do
  
    root to: 'pages#index'

    get "/coming_soon", to: "pages#coming_soon", as: :coming_soon
    
    get "/support", to: "pages#support", as: :support
    
    resources :pages, only: %i[index] 
  
    resources :articles, only: %i[index show]
    
    resources :stories, only: %i[index show]
    
    # dashboard
    get "/tutorials", to: "dashboard#tutorials", as: :tutorials
    get "/downloads", to: "dashboard#downloads", as: :downloads
    get "/forum", to: "dashboard#forum", as: :forum
    get "/form", to: "dashboard#form", as: :form
  
  end
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
     
  extend FriendlyId
  
  LANGUAGES = %w[ar en].freeze
  
  validates :title, presence: true, length: { minimum: 10 }
  validates :description, presence: true, length: { minimum: 100 }
  validates :locale,  inclusion: { in: LANGUAGES, allow_nil: false }
  
  friendly_id :title, use: :slugged
                                  
  mount_uploader :photo, PhotoUploader
  
  private
  
  def locale_enum
     %w[ar en]
  end
  
  def gravity_enum
     %w[north south east west ""]
  end

end

app/models/download.rb
class Download < ApplicationRecord
end

app/models/story.rb
class Story < ApplicationRecord
     
  extend FriendlyId
  
  LANGUAGES = %w[ar en].freeze
  
  validates :title, presence: true, length: { minimum: 10 }
  validates :description, presence: true, length: { minimum: 100 }
  validates :locale,  inclusion: { in: LANGUAGES, allow_nil: false }
  
  friendly_id :title, use: :slugged
                                  
  mount_uploader :photo, PhotoUploader
  
  private
  
  def locale_enum
     %w[ar en]
  end
  
  def gravity_enum
     %w[north south east west ""]
  end

end

app/models/tutorial.rb
class Tutorial < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  LANGUAGES = %w[ar en].freeze
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :email, email_format: { message: "doesn't look like an email address" }, presence: true
  validates :name, presence: true
  validates :locale, inclusion: LANGUAGES

  after_create :send_welcome_email
  after_create :subscribe_to_newsletter, if: :production_or_staging?
  
  def update_with_password(params={})
    if params[:password].blank?
      params.delete(:password)
      params.delete(:password_confirmation) if params[:password_confirmation].blank?
    end
    update_attributes(params)
  end

  private
  
  def admin?
    self.admin ? true : false
  end 
  
  def password_required?
    super if self.admin
  end

  def send_welcome_email
    Users::Creation::UserMailer.welcome(self.id).deliver_now
  end

  def subscribe_to_newsletter
    SubscribeToNewsletterService.new(self).call
  end

end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  skip_before_action :verify_authenticity_token
  
  around_action :set_locale
  
  include Pundit
  
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name mobile])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name mobile])
  end
  
  def skip_pundit? 
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
  
  def set_locale 
    I18n.locale = params[:locale] || current_user.try(:locale)
    yield
    I18n.locale = I18n.default_locale
  end
  
  def default_url_options
    { locale: I18n.locale == I18n.default_locale ? nil : I18n.locale }
  end
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  skip_before_action :authenticate_user!, only: %i[index show]
  
  def index
    # @articles = Article.where(locale: I18n.locale)
    @articles = Article.all
    policy_scope(Article)
  end

  def show
    @article = Article.friendly.find(params[:id])
    authorize @article
    if @article.youtube
      @video = Youtube.youtube_embed(@article.youtube)
    end 
  end

  private

  def article_params
    params.require(:article).permit(:title, :description, :locale, :photo, :photo_cache)
  end
    
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  
  def tutorials
    authorize(current_user)
  end
  
  def downloads
    authorize(current_user)
  end
  
  def forum
    authorize current_user
  end
  
  def form 
    authorize current_user
  end 
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  skip_before_action :authenticate_user!, only: %i[index support forum form]

  def index    
  end
  
  def support
  end 

  private

  def user_params
    params.require(:user).permit(:password, :password_confirmation, :name)
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  # def after_sign_up_path_for(resource)
  #   form_url
  # end
  
  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation).merge(locale: I18n.locale)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  
  skip_before_action :authenticate_user!, only: %i[index show]
  
  def index
    @stories = Story.where(locale: I18n.locale)
    @stories = Story.all
    policy_scope(Story)
  end

  def show
    @story = Story.friendly.find(params[:id])
    authorize @story
    if @story.youtube
      @video = Youtube.youtube_embed(@story.youtube)
    end 
  end

  private

  def story_params
    params.require(:story).permit(:title, :description, :locale, :photo, :photo_cache)
  end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def devise_page?
    (controller_name.in? %w[registrations sessions]) && action_name != 'edit'
  end 
  
  
  def homepage?
    (controller_name.in? %w[pages]) && action_name == 'index'
  end
  
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/dashboard/downloads.html.haml
- content_for :title, "Downloads"

#downloads-site
#main-content
  .container
    .description-center
    .row
      .col-xs-12.col-sm-10.col-sm-offset-1.col-md-10.col-md-offset-1
        .text-boxes
          .row.text-box.text-box-title-above
            .col-sm-12
              %h2
                = "Downloads"
              .toolbar
                .btn.btn-link>
            .row
              .col-sm-2
                = link_to asset_path("tutorials/Bolted_Clamp_Design.zip") do
                  = image_tag "download.png",                        
                    class: "img-responsive center-block img-rounded-half",                             
                    style: "margin: 20px 0 20px 0"                           
              .col-sm-10
                %h4
                  = "Version X.X.X"
                %p 
                  .i.fa.fa-calendar
                    10-12-17
                %p
                  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                = link_to "Download", asset_path("tutorials/Bolted_Clamp_Design.zip"), class: "btn btn-gray-transparent"
            %hr.hr-half
            .row
              .col-sm-2
                = link_to asset_path("tutorials/Bolted_Clamp_Design.zip") do
                  = image_tag "download.png",                        
                    class: "img-responsive center-block img-rounded-half",                             
                    style: "margin: 20px 0 20px 0"                           
              .col-sm-10
                %h4
                  = "Version X.X.X"
                %p 
                  .i.fa.fa-calendar
                    10-12-17
                %p
                  The object of this tutorial is to introduce users to a design checker that can be used to assess the design performance of tubular bolted clamps. The type of clamps that can be checked are those of the type commonly used to from a riser connections to offshore jackets and pipework support connections on subsea structures. The design checks are in accordance with the guidelines of OTH 88 283 or OSO 19902 or using specific interface friction coefficients.
                = link_to "Download", asset_path("tutorials/Bolted_Clamp_Design.zip"), class: "btn btn-gray-transparent"
          %hr.hr-half
#scroll-to-top.fade
  %i.fa.fa-chevron-up

app/views/dashboard/form.html.haml
:sass
  .prose 
    line-height: 35px !important
    font-weight: 200 !important
    font-size: 18px !important
    margin: 3.2rem 0 !important
  
:css

  br {
   display: block;
   margin: 6px 0;
   }


- content_for :title, "form"

-# #feedback-site
-# #main{:role => "main"}
-#   .hidden-xs.hidden-sm{class: "visiblr-md-* visible-lg-*"}
-#     .banner-small{style: "background-image: linear-gradient(-225deg, rgba(0,101,168,0.0) 0%, rgba(0,36,61,0.2) 50%), url('#{cl_image_path("open-icebergs/contact2.jpg", client_hints: true, transformation: [{gravity: "xy_center", height: 1800, width: 4500, x: 0, y: 5000, crop: "crop", dpr: "auto"}])}');"}
-#   .hidden-md.hidden-lg{class: "visible-xs-* visible-sm-*"}
-#     .banner-small{style: "background-image: linear-gradient(-225deg, rgba(0,101,168,0.0) 0%, rgba(0,36,61,0.2) 50%), url('#{cl_image_path("open-icebergs/contact2.jpg", client_hints: true, transformation: [{width: 2000, height: 1800, gravity: "xy_center", x: 6000, y: 2000, dpr: "auto", crop: "fill"}])}');"}
-#   .container
-#     %ol.breadcrumb
-#       %li
-#         %i.fa.fa-home.pr-10
-#         %a{:href => "/"}
-#           = t('.home')
-#       %li.active
-#         = "Support"
-#   .container
-#     .row
-#       .col-xs-12.col-sm-push-1.col-sm-10
-#         %div
-#           .row.text-box-title-above.text-box-big-image
-#             .col-sm-12
-#               %h1.article-title
-#                 = "Support"
-#               %p
-#                 %span
-#               %hr{:style => "margin-bottom:10px"}/
-#               .row
-#                 .col-sm-12.prose
-#                   %h8

              %div
                = link_to 'Back', root_path, class: "btn btn-gray-transparent", style: "margin-bottom: 20px"



      

app/views/dashboard/forum.html.haml
:sass
  .prose 
    line-height: 35px !important
    font-weight: 200 !important
    font-size: 18px !important
    margin: 3.2rem 0 !important
  
:css

  br {
   display: block;
   margin: 6px 0;
   }


- content_for :title, "forum"

#forum-site

.page-wrapper
  / background image
  / banner start
  / ================
  .pv-40.stats.padding-bottom-clear.parallax.dark-translucent-bg.background-img-7{style: "height: 100vh"}
    .container
      .row
        .col-md-8.text-center.col-md-offset-2.pv-20
          .object-non-visible{"data-animation-effect" => "fadeIn", "data-effect-delay" => "100"}
            / logo
            #logo.logo.text-center
              %h3.margin-clear
            / name-and-slogan
            
            %h1.page-title.text-center 
              = t('.coming_soon')
            .separator
            %p.text-center
            = "A FS2000 forum is comming soon" 
            %br
            	
            %ul.list-inline.mb-20.text-center
            / countdown start
            .countdown.clearfix
            / countdown end
      
      
            
          %div
            = link_to 'Back', root_path, class: "btn btn-gray-transparent", style: "margin-bottom: 20px"



      

app/views/dashboard/tutorials.html.haml
- content_for :title, "Tutorials"

#tutorials
#main-content
  .container
    .description-center
    .row
      .col-xs-12.col-sm-10.col-sm-offset-1.col-md-10.col-md-offset-1
        .text-boxes
          .row.text-box.text-box-title-above
            .col-sm-12
              %h2
                = "Tutorials"
              .toolbar
                .btn.btn-link>
            .row
              .col-sm-2
                = link_to asset_path("tutorials/Bolted_Clamp_Design.zip") do
                  = image_tag "download.png",                        
                    class: "img-responsive center-block img-rounded-half",                             
                    style: "margin: 20px 0 20px 0"                           
              .col-sm-10
                %h4
                  = "Bolted Clamp Design"
                %p
                  The object of this tutorial is to introduce users to a design checker that can be used to assess the design performance of tubular bolted clamps. The type of clamps that can be checked are those of the type commonly used to from a riser connections to offshore jackets and pipework support connections on subsea structures. The design checks are in accordance with the guidelines of OTH 88 283 or OSO 19902 or using specific interface friction coefficients.
                = link_to "Download", asset_path("tutorials/Bolted_Clamp_Design.zip"), class: "btn btn-gray-transparent"
            %hr.hr-half
            .row
              .col-sm-2
                = link_to asset_path("tutorials/Bolted_Clamp_Design.zip") do
                  = image_tag "download.png",                        
                    class: "img-responsive center-block img-rounded-half",                             
                    style: "margin: 20px 0 20px 0"                           
              .col-sm-10
                %h4
                  = "Bolted Clamp Design"
                %p
                  The object of this tutorial is to introduce users to a design checker that can be used to assess the design performance of tubular bolted clamps. The type of clamps that can be checked are those of the type commonly used to from a riser connections to offshore jackets and pipework support connections on subsea structures. The design checks are in accordance with the guidelines of OTH 88 283 or OSO 19902 or using specific interface friction coefficients.
                = link_to "Download", asset_path("tutorials/Bolted_Clamp_Design.zip"), class: "btn btn-gray-transparent"
          %hr.hr-half
#scroll-to-top.fade
  %i.fa.fa-chevron-up

app/views/layouts/application.html.haml
!!!
%html{lang: I18n.locale}
  %head
    - if test?
      :javascript
        window.errors = []
        window.onerror = function(a, b, c){
          window.errors.push([a, b, c]);
          return false; // false: don't swallow exceptions.
        }
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title= yield(:title)
    = render 'shared/favicon'
    = csrf_meta_tags
    = action_cable_meta_tag
    %meta{:content => "IE=edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %meta{:charset => "utf-8"}/
    / Mobile Meta
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    / Web Fonts
    %link{:href => "https://fonts.googleapis.com/css?family=Roboto:400,300,300italic,400italic,500,500italic,700,700italic", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "https://fonts.googleapis.com/css?family=Raleway:700,400,300", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "https://fonts.googleapis.com/css?family=Pacifico", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "https://fonts.googleapis.com/css?family=PT+Serif", :rel => "stylesheet", :type => "text/css"}/
    = stylesheet_link_tag    'application', media: 'all'
  
  / body classes:
  / "boxed": boxed layout mode e.g. <body class="boxed">
  / "pattern-1 ... pattern-9": background patterns for boxed layout mode e.g. <body class="boxed pattern-1">
  / "transparent-header": makes the header transparent and pulls the banner to top
  / "gradient-background-header": applies gradient background to header
  / "page-loader-1 ... page-loader-6": add a page loader to the page (more info @components-page-loaders.html)
  %body.front-page
    .scrollToTop.circle
      %i.icon-up-open-big
    .page-wrapper
      / header-top start
      / classes:
      / "dark": dark version of header top e.g. class="header-top dark"
      / "colored": colored version of header top e.g. class="header-top colored"
      / ================
      - if homepage?
        = render 'shared/navbar_top'
        = render 'shared/navbar'
      - else 
        = render 'shared/navbar_dashboard'
      = render 'shared/flashes'
      = yield
      = render 'shared/footer' unless devise_page?
  
    = javascript_include_tag 'application'
    = yield(:after_js)
    
    -# google analitics
    :javascript
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-89702518-5', 'auto');
      ga('send', 'pageview');
      
    -# userback
    :javascript
      Userback = window.Userback || {};
      Userback.access_token = "#{ENV["USERBACK_TOKEN"]}";

      (function(id) {
          if (document.getElementById(id)) {return;}
          var s = document.createElement('script');
          s.id = id;
          s.src = 'https://static.userback.io/widget/v1.js';
          var parent_node = document.head || document.body;
          parent_node.appendChild(s);
      })('userback-sdk');

app/views/pages/_contact.html.haml
:sass

#contact_us.linked
%section.section.pv-40.clearfix
  .container
    .row
      .col-md-8.col-md-offset-2
        %h3.title.text-center
          Sales
          %span.text-default
        .separator
        %p.lead.text-center


    .row
      .col-lg-6
        %h3.title
        %p
          Licenses are available on a single payment perpetual license basis with optional technical and upgrade support or a lease basis which includes both technical and upgrade support. The minimum lease period is 3 months.
          %br
          %br
          If you require license costs or any additional information on the NWD modules please contact AES  on
          = succeed "" do
            %a{:href => "sales@newwavesdesign.com"}
              sales@newwavesdesign.com.
        %ul.list-icons
          %li.object-non-visible{"data-animation-effect" => "fadeInUpSmall", "data-effect-delay" => "100"}
            %i.icon-check-1
            Low cost
          %li.object-non-visible{"data-animation-effect" => "fadeInUpSmall", "data-effect-delay" => "100"}
            %i.icon-check-1
            Local or floating licenses (licences can be shared between office locations)
          %li.object-non-visible{"data-animation-effect" => "fadeInUpSmall", "data-effect-delay" => "150"}
            %i.icon-check-1
            Modules are fully integrated and the system can be added to on an 'as and when requirements dictate' basis.
          %li.object-non-visible{"data-animation-effect" => "fadeInUpSmall", "data-effect-delay" => "200"}
            %i.icon-check-1
            Support is provided free of charge for a period of 6 months from date of purchase.
          %li.object-non-visible{"data-animation-effect" => "fadeInUpSmall", "data-effect-delay" => "250"}
            %i.icon-check-1
            Technical support is available to all registered users.

      .col-lg-6.mb-4
        .overlay-container.overlay-visible{style: "margin-top: 20px"}
          = cl_image_tag("fs2000/field.jpg", :client_hints=>true, :transformation=>[{:dpr=>"auto", :height=>1250, :width=>2000, :y=>100, :x=>150, :crop=>"fill"}])

%section.section.video-background.background-img-1.default-translucent-bg
  .container
    .row
      .col-md-12
        .call-to-action.text-center
          .row
            .col-sm-8
              %h1.title Learn NWD in 1 day
              %p Your all-in-one solution for advanced and simple pipeline, structural and pipework analyses.
            .col-sm-4
              %br/
              %p
                %a.btn.btn-lg.btn-gray-transparent.btn-animated{:href => "#"}
                  Free trial
                  %i.fa.fa-arrow-right.pl-20

app/views/pages/index.html.haml
/ scrollToTop
/ ================

:sass
  .linked
    display: block
    position: relative
    top: -45px
    visibility: hidden
      
  .top-margin
    margin: 20px 0 0 0 !important


- content_for :title, I18n.t('views.project_title')

.front-page
= render 'home'
= render 'main_features'
= render 'clients'
= render 'modular_approach'
= render 'contact'

app/views/pages/support.html.haml
:sass
  .prose
    line-height: 35px !important
    font-weight: 200 !important
    font-size: 18px !important
    margin: 3.2rem 0 !important

:css

  br {
   display: block;
   margin: 6px 0;
   }


- content_for :title, "Support"

#support-site
#main{:role => "main"}
  .hidden-xs.hidden-sm{class: "visiblr-md-* visible-lg-*"}
    .banner-small{style: "background-image: linear-gradient(-225deg, rgba(0,101,168,0.0) 0%, rgba(0,36,61,0.2) 50%), url('#{cl_image_path("open-icebergs/contact2.jpg", client_hints: true, transformation: [{gravity: "xy_center", height: 1800, width: 4500, x: 0, y: 5000, crop: "crop", dpr: "auto"}])}');"}
  .hidden-md.hidden-lg{class: "visible-xs-* visible-sm-*"}
    .banner-small{style: "background-image: linear-gradient(-225deg, rgba(0,101,168,0.0) 0%, rgba(0,36,61,0.2) 50%), url('#{cl_image_path("open-icebergs/contact2.jpg", client_hints: true, transformation: [{width: 2000, height: 1800, gravity: "xy_center", x: 6000, y: 2000, dpr: "auto", crop: "fill"}])}');"}
  .container
    %ol.breadcrumb
      %li
        %i.fa.fa-home.pr-10
        %a{:href => "/"}
          = t('.home')
      %li.active
        = "Support"
  .container
    .row
      .col-xs-12.col-sm-push-1.col-sm-10
        %div
          .row.text-box-title-above.text-box-big-image
            .col-sm-12
              %h1.article-title
                = "Support"
              %p
                %span
              %hr{:style => "margin-bottom:10px"}/
              .row
                .col-sm-12.prose
                  %h8
                    We deliver support and education by providing on-site training,
                    %span
                      = link_to "tutorials", tutorials_path
                    and access to
                    %span
                      = link_to "NWD knowledge forum.", tutorials_path
                    %br
                    Technical support by phone is available to all registered users.
                  #training
                  %h3
                    = "1. Training"
                  %h8
                    We can provide on-site training in the use of NWD geared directly to your specific analysis requirements.
                    %br
                    In addition to demonstrating the use of NWD we can also provide the user with a basic understanding of the fundamentals of structural modeling, its application and limitations relevant to typical or specific component designs.
                    %br
                    Training case studies need not be restricted to academic examples. Current design problems or design justifications may be used as case studies so that training not only gets the users 'up to speed' with NWD but also 'gets the job done'.
                    %br
                    If you require any additional information on NWD training please contact us at
                    = succeed "" do
                      %a{:href => "sales@newwavesdesign.com"}
                        sales@newwavesdesign.com.
                  #tutorials
                  %h3
                    = "2. Tutorials"
                  %h8
                    A comprehensive list of tutorials can be accessed
                    = succeed "" do
                      %a{:href => "/"}
                        here,
                    covering most of the aspects that engineers encounter in the subsea and offshore industry.
                  #forum
                  %h3
                    = "3. Knowledge forum"
                  %h8
                    Access to the forum can be accessed
                    = succeed "" do
                      %a{:href => "/"}
                        here.
                    %br
                    We review daily the queries that NWD users post and answer them, if other NWD have not answer them already.
                    %br

                    The forum provides an excellent environment for learning from the worldwide community of NWD users, as well as having direct access to the most common questions that new users encounter when using NWD.


              %div
                = link_to 'Back', root_path, class: "btn btn-gray-transparent", style: "margin-bottom: 20px"

app/views/shared/_flashes.html.haml
- if notice
  .alert.alert-info.alert-dismissible{:role => "alert"}
    %button.close{"aria-label" => "Close", "data-dismiss" => "alert", :type => "button"}
      %span{"aria-hidden" => "true"} ×
    = notice
- if alert
  .alert.alert-warning.alert-dismissible{:role => "alert"}
    %button.close{"aria-label" => "Close", "data-dismiss" => "alert", :type => "button"}
      %span{"aria-hidden" => "true"} ×
    = alert

app/views/shared/_navbar_top.html.haml
/ header-top start
/ classes:
/ "dark": dark version of header top e.g. class="header-top dark"
/ "colored": colored version of header top e.g. class="header-top colored"
/ ================
.header-top.colored
  .container
    .row
      .col-2.col-md-5
        / header-top-first start
        / ================
        .header-top-first.clearfix
          %ul.social-links.circle.small.clearfix.hidden-sm-down
            %li.linkedin
              -# %a{:href => "http://www.linkedin.com", :target => "_blank"}
                %i.fa.fa-linkedin
          -# %ul.list-inline
          -#   %li.list-inline-item
          -#     %i.fa.fa-envelope-o.pr-1.pl-10
          -#     contact@FS2000.com
          .social-links.hidden-md-up.circle.small
            .btn-group.dropdown
              %ul.dropdown-menu.dropdown-animation{"aria-labelledby" => "header-top-drop-1"}
                %li.linkedin
                  %a{:href => "http://www.linkedin.com", :target => "_blank"}
                    %i.fa.fa-linkedin
        / header-top-first end
      .col-10.col-md-7
        / header-top-second start
        / ================
        #header-top-second.clearfix.text-right
          -# .btn-group
          -#   %a.btn.btn-default.btn-sm{:href => "page-signup.html"}
          -#     %i.fa.fa-user.pl-2
          -#     Sign Up
          - if current_user.try(:admin?)
            = link_to "/admin" do
              %button#header-top-drop-2.btn.dropdown-toggle.btn-default.btn-sm.dropdown-toggle--no-caret
                %i.fa.fa-lock.pl-2
                Admin panel
          - if current_user
            = link_to tutorials_path do
              %button#header-top-drop-2.btn.dropdown-toggle.btn-default.btn-sm.dropdown-toggle--no-caret#dashboard
                Dashboard access
          - else
            = link_to new_user_session_path do
              %button#header-top-drop-2.btn.dropdown-toggle.btn-default.btn-sm.dropdown-toggle--no-caret#login
                %i.fa.fa-user.pl-2
                Login
        / header-top-second end
/ header-top end